name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        - 1.14.x
        - 1.15.x
        - 1.16.x
        - 1.17.x
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        stable: 'true'
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -race ./... -v
